name: cicd for dev

on:
  push:
    branches: ['develop']
env:
  IMAGE_NAME: chatgpt-web-midjourney-proxy
  IMAGE_TAG: dev
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Build and push the image
        run: |
          docker login --username deniel369 --password ${{ secrets.FEDAG_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/fedagcom/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ghcr.io/fedagcom/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: executing remote ssh commands 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FEDAG_SSH_HOST }}
          username: ${{ secrets.FEDAG_SSH_USER }}
          password: ${{ secrets.FEDAG_SSH_PASSWORD }}
          port: ${{ secrets.FEDAG_SSH_PORT }}
          script: |
            cd /home
            touch .env-suno
            echo SESSION_ID=${{ secrets.SUNO__BASE_URL }} >> .env-suno
            echo BASE_URL=${{ secrets.SUNO__SESSION_ID }} >> .env-suno
            echo COOKIE=${{ secrets.SUNO__COOKIE }} >> .env-suno
            cd /../
            cd ${{ secrets.FEDAG_SSH_FOLDER }}
            docker compose down
            docker rmi ghcr.io/fedagcom/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker compose up -d
      
